general {
    lock_cmd = pidof hyprlock || hyprlock
  }

listener {
    timeout = 600     #10 min
    on-timeout = loginctl lock-session     # lock screen after 10min idle
  }


listener {
    timeout = 150                                # 2.5min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

